### ISSUE TITLE
Create a system to manage multiple accounts

### ISSUE THREAD

**Issue by Arihant25** [Arihant25/class-link-check#3]
Right now, the user needs to choose an account manually when the class has started.
We need a setting to allow the user to select a default account for use with meetings.

**Comment by Arihant25** [comment]
Instead of adding another setting to choose accounts, use the last chosen account as the default account. 
This will avoid making the UI cluttered and changing the UI repeatedly (leading to remaking the screenshots and other promotional material).

**Comment by AmiMappy** [comment]
We should ask users to use [this extension](https://chrome.google.com/webstore/detail/classroom-redirector/cnapdogghpeenfmlficdcbhflhemeoob) in tandem with our extension.
