### ISSUE TITLE
Choose Account notification persists even after choosing account

### ISSUE THREAD

**Issue by Arihant25** [Arihant25/class-link-check#5]

**Comment by AmiMappy** [comment]
could you describe it further? perhaps with screenshot(s) and/or video(s)

**Comment by Arihant25** [comment]
Steps to Reproduce:
1. Let it open the choose account page
2. Choose an account
3. The meeting page loads, but you again get a notification to choose an account.

**Comment by AmiMappy** [comment]
why, i shall look into it then

**Comment by AmiMappy** [comment]
i followed the steps and was not able to reproduce the problem. after i have chosen an account, it does notify me that the class has begun, but not about choosing an account.
kindly install the latest version from the repo and let us know if the problem persists.

**Comment by Arihant25** [comment]
Hmmm, it seems to have been fixed in the latest version. 🥳

**Comment by AmiMappy** [comment]
Actually, you'll see that it will show up again. I am going to put up two-three versions of each content script so that if one doesn't work, the others might. I just fixed the error be re-adding a code snippet that I thought was the bug for a previous issue.
